services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
  frontend:
    container_name: frontend-wc
    image: node:18
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: bash -c "npm i -g vite && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
volumes:
  db-data:
